site_name: Веб-терминал
nav:
  - 'Терминал':
      - 'Предложения и вопросы': '1.md'
  - 'Общее':
      - 'Виджеты': 'widgets.md'
      - 'Группы': '1.md'
      - 'Вкладки в терминале': '1.md'
      - 'Верхняя панель': '1.md'
      - 'Нижняя панель': '1.md'
  - 'Виджеты':
      - 'График': '1.md'
      - 'Индикаторы': '1.md'
      - 'Устаревший график': '1.md'
      - 'Заявка': '1.md'
      - 'Отложенная заявка': '1.md'
      - 'Активные заявки': '1.md'
      - 'Портфель': '1.md'
      - 'Подписки': '1.md'
      - 'Об инструменте': '1.md'
      - 'Инструменты': '1.md'
      - 'Операции': '1.md'
      - 'Стакан': '1.md'
      - 'Скринер': '1.md'
      - 'Маржинальная торговля': '1.md'
      - 'Лента': '1.md'
      - 'Календарь инвестора': '1.md'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    